[package]
name = "remyx-widgets"
version = "0.3.1-remyx.2"
description = "A collection of Ratatui widgets for building terminal user interfaces using Ratatui."
documentation = "https://docs.rs/remyx-widgets"
readme = "README.md"
authors = ["Florian Dehau", "The Ratatui Developers", "Manuel Garcia de la Vega"]
repository = "https://github.com/remyx-rs/ratatui-widgets"
homepage = "https://ratatui.rs"
keywords = ["dashboard", "terminal", "tui"]
categories = ["command-line-interface"]
license = "MIT"
edition = "2024"
rust-version = "1.88.0"

[features]
default = ["all-widgets"]
std = ["serde?/std", "time?/local-offset"]
serde = ["dep:serde", "ratatui-core/serde"]
all-widgets = ["calendar"]
calendar = ["dep:time"]
unstable = ["unstable-rendered-line-info"]
unstable-rendered-line-info = []

[dependencies]
bitflags = "2.12"
document-features = { version = "0.2", optional = true }
hashbrown = "0.17"
indoc = "2"
instability = "0.3"
itertools = { version = "0.14", default-features = false, features = ["use_alloc"] }
line-clipping = "0.3"
ratatui-core = "0.1.1"
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
strum = { version = "0.28", default-features = false, features = ["derive"] }
time = { version = "0.3.47", default-features = false, optional = true }
unicode-segmentation = "1"
unicode-width = ">=0.2.0"

[dev-dependencies]
color-eyre = "0.6"
crossterm = "0.29"
pretty_assertions = "1"
ratatui = "0.30.1"
rstest = "0.26"

[lints.rust]
unsafe_code = "forbid"
